#!/bin/bash

zscroll -l 37 \
-p " / " \
--delay 0.2 \
--match-command "playerctl status" \
--match-text "Playing" "--scroll 1" \
--match-text "Paused" "--scroll 0" \
--update-check true 'playerctl metadata --format "{{ artist }} - {{ title }}"'
