#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many \
		   background \
		   profile \
		   system \
		   fetch \
		   launcher \
		   music \
		   calendar \
		   but1 \
		   time \
		   colors \
		   pb \
		   pr \
		   ps \
		   volume \
		   brightness
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
					background profile system fetch launcher music calendar \
					but1 time colors pb pr ps volume brightness
	rm "$FILE"
fi
